slam_toolbox:
    ros__parameters:
        mode: "localization" # 设置为定位模式
        use_sim_time: false
        map_frame: map
        odom_frame: odom
        base_frame: base_link
        scan_topic: scan # 激光雷达扫描话题
        transform_publish_period: 0.05
        map_update_interval: 5.0
        publish_tf: true 
