laser_scan_matcher:
  ros__parameters:
    scan_topic: "/scan"
    odom_frame: "odom"
    base_frame: "laser_link"
    publish_odom: true
    max_angular_correction_deg: 10.0  # 限制角度变化范围
    max_linear_correction: 0.2        # 限制位移变化范围
    max_iterations: 10                # 设置匹配迭代次数
    epsilon_xy: 0.0001                # 设置线性收敛阈值
    epsilon_theta: 0.0001             # 设置角度收敛阈值
    use_sim_time: False
